// Code generated by pt-gen-go; DO NOT EDIT.

package golden

import (
	"github.com/domenukk/md-tmpl/go/md_tmpl"
)

// Priority is a string enum type.
type Priority string

const (
	// PriorityCritical is the "Critical" variant.
	PriorityCritical Priority = "Critical"
	// PriorityHigh is the "High" variant.
	PriorityHigh Priority = "High"
	// PriorityMedium is the "Medium" variant.
	PriorityMedium Priority = "Medium"
	// PriorityLow is the "Low" variant.
	PriorityLow Priority = "Low"
)

// PriorityVariants lists every value of Priority, in declaration order.
var PriorityVariants = []Priority{PriorityCritical, PriorityHigh, PriorityMedium, PriorityLow}

// TasksItem is a nested type for structured fields.
type TasksItem struct {
	Name    string   `json:"name"`
	Urgency Priority `json:"urgency"`
}

// TaskReportParams holds the typed parameters for template rendering.
type TaskReportParams struct {
	// Title parameter.
	Title string `json:"title"`
	// Priority parameter.
	Priority Priority `json:"priority"`
	// Tasks parameter.
	Tasks []TasksItem `json:"tasks"`
}

// Render renders the template with these typed parameters.
//
// Scalar fields use direct FFI setters (no reflection or serialization).
// Complex fields (list, struct, enum) are set via FlexBuffers encoding.
func (p TaskReportParams) Render(tmpl *md_tmpl.Template) (string, error) {
	ctx := md_tmpl.NewContext()
	defer ctx.Close()
	if err := ctx.SetStr("title", string(p.Title)); err != nil {
		return "", err
	}
	if err := ctx.Set("priority", p.Priority); err != nil {
		return "", err
	}
	if err := ctx.Set("tasks", p.Tasks); err != nil {
		return "", err
	}
	return tmpl.Render(ctx)
}
