package md_tmpl

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// GenOption configures code generation via the functional options pattern.
type GenOption func(*genOptions)

type genOptions struct {
	packageName  string
	paramsName   string
	renderHelper bool
}

func defaultGenOptions() *genOptions {
	return &genOptions{
		packageName:  "main",
		paramsName:   "",
		renderHelper: true,
	}
}

// WithPackageName sets the Go package name in the generated source.
// Default: "main".
func WithPackageName(name string) GenOption {
	return func(o *genOptions) { o.packageName = name }
}

// WithParamsName sets the name of the generated params struct.
// Default: derived from the file stem in PascalCase + "Params".
// When generating from source (no filename), defaults to "Params".
func WithParamsName(name string) GenOption {
	return func(o *genOptions) { o.paramsName = name }
}

// WithRenderHelper controls whether a Render helper method is generated.
// Default: true.
func WithRenderHelper(include bool) GenOption {
	return func(o *genOptions) { o.renderHelper = include }
}

// GenerateTypes generates Go source code from a template source string.
//
// The source must include YAML frontmatter with parameter declarations.
// Returns valid, gofmt-formatted Go source code as a string.
func GenerateTypes(source string, opts ...GenOption) (string, error) {
	o := defaultGenOptions()
	for _, fn := range opts {
		fn(o)
	}
	if o.paramsName == "" {
		o.paramsName = "Params"
	}

	tmpl, err := FromSource(source, WithAllowUnused())
	if err != nil {
		return "", fmt.Errorf("parsing template source: %w", err)
	}
	defer tmpl.Close()

	return generateFromTemplate(tmpl, o)
}

// GenerateTypesFromFile generates Go source code from a .tmpl.md file.
//
// The params struct name defaults to PascalCase(fileStem) + "Params"
// unless overridden with [WithParamsName].
func GenerateTypesFromFile(path string, opts ...GenOption) (string, error) {
	o := defaultGenOptions()
	for _, fn := range opts {
		fn(o)
	}
	if o.paramsName == "" {
		stem := strings.TrimSuffix(filepath.Base(path), ".tmpl.md")
		if stem == filepath.Base(path) {
			stem = strings.TrimSuffix(stem, filepath.Ext(stem))
		}
		o.paramsName = toPascalCase(stem) + "Params"
	}

	source, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading template file: %w", err)
	}

	tmpl, err := FromSource(string(source), WithAllowUnused())
	if err != nil {
		return "", fmt.Errorf("parsing template file: %w", err)
	}
	defer tmpl.Close()

	return generateFromTemplate(tmpl, o)
}

// ---------------------------------------------------------------------------
// Code generation core
// ---------------------------------------------------------------------------

type emittedEnum struct {
	name     string
	variants []variantNode
}

// codegenContext accumulates generated Go source pieces.
type codegenContext struct {
	opts           *genOptions
	auxiliaryTypes []string        // Nested struct/enum definitions.
	generatedNames map[string]bool // Dedup set for generated type names.
	emittedEnums   []emittedEnum   // Structural deduplication for emitted enum types.

	// Import requirements discovered while resolving types. Sealed enum
	// output references the md_tmpl runtime, encoding/json, and fmt.
	needsMdTmpl bool
	needsJSON   bool
	needsFmt    bool
}

func newCodegenContext(opts *genOptions) *codegenContext {
	return &codegenContext{
		opts:           opts,
		generatedNames: make(map[string]bool),
	}
}

// requiredImports returns the import paths the generated file references, sorted
// so the output is stable and gofmt-clean.
func (c *codegenContext) requiredImports() []string {
	var imports []string
	if c.needsJSON {
		imports = append(imports, "encoding/json")
	}
	if c.needsFmt {
		imports = append(imports, "fmt")
	}
	if c.needsMdTmpl {
		imports = append(imports, "github.com/domenukk/md-tmpl/go/md_tmpl")
	}
	sort.Strings(imports)
	return imports
}

func generateFromTemplate(tmpl *Template, opts *genOptions) (string, error) {
	decls := tmpl.Declarations()

	ctx := newCodegenContext(opts)
	ctx.needsMdTmpl = opts.renderHelper

	// First pass: resolve all types (may generate auxiliary definitions).
	type fieldInfo struct {
		name     string
		goType   string
		typeKind typeKind // Retained for generating optimal setter calls.
	}
	fields := make([]fieldInfo, 0, len(decls))
	for _, d := range decls {
		parsed, err := parseTypeSpec(d.Type)
		if err != nil {
			return "", fmt.Errorf("parsing type for %q: %w", d.Name, err)
		}
		goType := ctx.resolveType(d.Name, parsed)
		fields = append(fields, fieldInfo{name: d.Name, goType: goType, typeKind: parsed.kind})
	}

	// Build the output.
	var b strings.Builder

	b.WriteString("// Code generated by pt-gen-go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.packageName)

	// Imports — computed from what the generated code actually references.
	if imports := ctx.requiredImports(); len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			fmt.Fprintf(&b, "\t%q\n", imp)
		}
		b.WriteString(")\n\n")
	}

	// Auxiliary types (enums, nested structs).
	for _, aux := range ctx.auxiliaryTypes {
		b.WriteString(aux)
		b.WriteString("\n\n")
	}

	// Main params struct.
	fmt.Fprintf(&b, "// %s holds the typed parameters for template rendering.\n", opts.paramsName)
	fmt.Fprintf(&b, "type %s struct {\n", opts.paramsName)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t// %s parameter.\n", toPascalCase(f.name))
		fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", toPascalCase(f.name), f.goType, f.name)
	}
	b.WriteString("}\n")

	// Render helper method — emit direct SetStr/SetInt/etc. calls for scalar
	// fields to bypass reflect + FlexBuffers serialization entirely.
	if opts.renderHelper {
		b.WriteString("\n")
		fmt.Fprintf(&b, "// Render renders the template with these typed parameters.\n")
		fmt.Fprintf(&b, "//\n")
		fmt.Fprintf(&b, "// Scalar fields use direct FFI setters (no reflection or serialization).\n")
		fmt.Fprintf(&b, "// Complex fields (list, struct, enum) are set via FlexBuffers encoding.\n")
		fmt.Fprintf(&b, "func (p %s) Render(tmpl *md_tmpl.Template) (string, error) {\n", opts.paramsName)
		b.WriteString("\tctx := md_tmpl.NewContext()\n")
		b.WriteString("\tdefer ctx.Close()\n")
		for _, f := range fields {
			goField := toPascalCase(f.name)
			switch f.typeKind {
			case kindStr:
				fmt.Fprintf(&b, "\tif err := ctx.SetStr(%q, string(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindInt:
				fmt.Fprintf(&b, "\tif err := ctx.SetInt(%q, int64(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindFloat:
				fmt.Fprintf(&b, "\tif err := ctx.SetFloat(%q, float64(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindBool:
				fmt.Fprintf(&b, "\tif err := ctx.SetBool(%q, bool(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindTmpl:
				fmt.Fprintf(&b, "\tif err := ctx.SetTmpl(%q, p.%s); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			default:
				// Complex types (list, struct, enum): use generic Set which
				// marshals via FlexBuffers — still a single FFI call.
				fmt.Fprintf(&b, "\tif err := ctx.Set(%q, p.%s); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			}
		}
		b.WriteString("\treturn tmpl.Render(ctx)\n")
		b.WriteString("}\n")
	}

	// Format with gofmt.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return b.String(), fmt.Errorf("formatting generated code: %w\n\nRaw output:\n%s", err, b.String())
	}
	return string(formatted), nil
}

func equalTypeNode(a, b typeNode) bool {
	if a.kind != b.kind || a.aliasName != b.aliasName {
		return false
	}
	if (a.innerType == nil) != (b.innerType == nil) {
		return false
	}
	if a.innerType != nil && !equalTypeNode(*a.innerType, *b.innerType) {
		return false
	}
	if len(a.fields) != len(b.fields) {
		return false
	}
	for i := range a.fields {
		if a.fields[i].name != b.fields[i].name || !equalTypeNode(a.fields[i].typeNode, b.fields[i].typeNode) {
			return false
		}
	}
	return equalVariants(a.variants, b.variants)
}

func equalVariants(a, b []variantNode) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i].name != b[i].name || len(a[i].fields) != len(b[i].fields) {
			return false
		}
		for j := range a[i].fields {
			if a[i].fields[j].name != b[i].fields[j].name ||
				!equalTypeNode(a[i].fields[j].typeNode, b[i].fields[j].typeNode) {
				return false
			}
		}
	}
	return true
}

// resolveType converts a parsed typeNode into a Go type string, emitting
// auxiliary type definitions as needed.
func (c *codegenContext) resolveType(fieldName string, node typeNode) string {
	switch node.kind {
	case kindStr:
		return "string"
	case kindInt:
		return "int64"
	case kindFloat:
		return "float64"
	case kindBool:
		return "bool"

	case kindList:
		if len(node.fields) == 0 {
			return "[]any"
		}
		itemName := toPascalCase(fieldName) + "Item"
		c.emitStruct(itemName, node.fields)
		return "[]" + itemName

	case kindStruct:
		if len(node.fields) == 0 {
			return "map[string]any"
		}
		structName := toPascalCase(fieldName)
		c.emitStruct(structName, node.fields)
		return structName

	case kindEnum:
		for _, existing := range c.emittedEnums {
			if equalVariants(existing.variants, node.variants) {
				return existing.name
			}
		}
		enumName := toPascalCase(fieldName)
		c.emittedEnums = append(c.emittedEnums, emittedEnum{name: enumName, variants: node.variants})
		c.emitEnum(enumName, node.variants)
		return enumName

	case kindOption:
		if node.innerType == nil {
			return "*string"
		}
		inner := c.resolveType(fieldName, *node.innerType)
		if node.innerType.kind == kindTmpl {
			return inner
		}
		if node.innerType.kind == kindEnum {
			isInterface := false
			for _, v := range node.innerType.variants {
				if len(v.fields) > 0 {
					isInterface = true
					break
				}
			}
			if isInterface {
				return inner
			}
		}
		if strings.HasPrefix(inner, "*") {
			return inner
		}
		return "*" + inner

	case kindScalarList:
		if node.innerType == nil {
			return "[]any"
		}
		inner := c.resolveType(fieldName, *node.innerType)
		return "[]" + inner

	case kindTmpl:
		c.needsMdTmpl = true
		return "*md_tmpl.Template"

	case kindAlias:
		if node.aliasName != "" {
			return toPascalCase(node.aliasName)
		}
		return "string"

	default:
		return "string"
	}
}

// emitStruct generates a Go struct type for list items or struct values.
func (c *codegenContext) emitStruct(name string, fields []fieldNode) {
	if c.generatedNames[name] {
		return
	}
	c.generatedNames[name] = true

	var b strings.Builder
	fmt.Fprintf(&b, "// %s is a nested type for structured fields.\n", name)
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, f := range fields {
		goType := c.resolveType(f.name, f.typeNode)
		fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", toPascalCase(f.name), goType, f.name)
	}
	b.WriteString("}")

	c.auxiliaryTypes = append(c.auxiliaryTypes, b.String())
}

// emitEnum generates Go type definitions for an enum.
func (c *codegenContext) emitEnum(name string, variants []variantNode) {
	if c.generatedNames[name] {
		return
	}
	c.generatedNames[name] = true

	// Check if all variants are unit (no fields).
	allUnit := true
	for _, v := range variants {
		if len(v.fields) > 0 {
			allUnit = false
			break
		}
	}

	if allUnit {
		c.emitUnitEnum(name, variants)
	} else {
		c.emitMixedEnum(name, variants)
	}
}

// emitUnitEnum generates a string-based enum with a const block and a slice of
// all variants for ergonomic enumeration.
func (c *codegenContext) emitUnitEnum(name string, variants []variantNode) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s is a string enum type.\n", name)
	fmt.Fprintf(&b, "type %s string\n\n", name)
	fmt.Fprintf(&b, "const (\n")
	for _, v := range variants {
		constName := name + v.name
		fmt.Fprintf(&b, "\t// %s is the %q variant.\n", constName, v.name)
		fmt.Fprintf(&b, "\t%s %s = %q\n", constName, name, v.name)
	}
	b.WriteString(")\n\n")

	// A slice of every variant, in declaration order, for iteration/validation.
	fmt.Fprintf(&b, "// %sVariants lists every value of %s, in declaration order.\n", name, name)
	fmt.Fprintf(&b, "var %sVariants = []%s{", name, name)
	for i, v := range variants {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(name + v.name)
	}
	b.WriteString("}")

	c.auxiliaryTypes = append(c.auxiliaryTypes, b.String())
}

// emitMixedEnum generates an idiomatic Go sum type (a sealed interface plus one
// struct per variant) for enums that contain at least one data variant.
//
// Each variant carries Kind, AsVariant, and MarshalJSON so it serializes to the
// shared cross-language wire format — a bare string for unit variants, a
// {"__kind__": "...", ...fields} object for data variants — through both the
// FlexBuffers render path and encoding/json. A companion Unmarshal<Name> reads
// either wire form back into the sealed interface.
func (c *codegenContext) emitMixedEnum(name string, variants []variantNode) {
	// Sealed enums reference the runtime Variant type, encoding/json, and fmt.
	c.needsMdTmpl = true
	c.needsJSON = true
	c.needsFmt = true

	sealMethod := "is" + name

	var b strings.Builder

	// Sealed interface.
	fmt.Fprintf(&b, "// %s is a sum type (sealed interface).\n", name)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Variants:\n")
	for _, v := range variants {
		fmt.Fprintf(&b, "//   - %s%s\n", name, v.name)
	}
	fmt.Fprintf(&b, "type %s interface {\n", name)
	fmt.Fprintf(&b, "\t%s()\n", sealMethod)
	fmt.Fprintf(&b, "\t// Kind returns the variant's discriminant name.\n")
	fmt.Fprintf(&b, "\tKind() string\n")
	fmt.Fprintf(&b, "\t// AsVariant returns the dynamic __kind__-tagged wire representation.\n")
	fmt.Fprintf(&b, "\tAsVariant() md_tmpl.Variant\n")
	b.WriteString("}\n\n")

	// A slice of every variant name, in declaration order.
	fmt.Fprintf(&b, "// %sVariants lists every variant name of %s, in declaration order.\n", name, name)
	fmt.Fprintf(&b, "var %sVariants = []string{", name)
	for i, v := range variants {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", v.name)
	}
	b.WriteString("}\n\n")

	// One struct + method set per variant.
	for _, v := range variants {
		c.emitVariantType(&b, name, sealMethod, v)
	}

	// Unmarshal dispatcher.
	c.emitVariantUnmarshaler(&b, name, variants)

	result := strings.TrimRight(b.String(), "\n")
	c.auxiliaryTypes = append(c.auxiliaryTypes, result)
}

// emitVariantType writes the struct definition, sealed-interface methods,
// AsVariant/MarshalJSON serializers, and a constructor for a single variant.
func (c *codegenContext) emitVariantType(b *strings.Builder, enumName, sealMethod string, v variantNode) {
	typeName := enumName + v.name

	// Struct definition.
	if len(v.fields) == 0 {
		fmt.Fprintf(b, "// %s is the %q unit variant of %s.\n", typeName, v.name, enumName)
		fmt.Fprintf(b, "type %s struct{}\n\n", typeName)
	} else {
		fmt.Fprintf(b, "// %s is the %q variant of %s.\n", typeName, v.name, enumName)
		fmt.Fprintf(b, "type %s struct {\n", typeName)
		b.WriteString("\tmd_tmpl.TaggedVariant\n")
		for _, f := range v.fields {
			goType := c.resolveType(f.name, f.typeNode)
			fmt.Fprintf(b, "\t%s %s `json:%q`\n", toPascalCase(f.name), goType, f.name)
		}
		b.WriteString("}\n\n")
	}

	// Sealed marker + Kind.
	fmt.Fprintf(b, "func (%s) %s() {}\n\n", typeName, sealMethod)
	fmt.Fprintf(b, "// Kind returns the discriminant name %q.\n", v.name)
	fmt.Fprintf(b, "func (%s) Kind() string { return %q }\n\n", typeName, v.name)

	// AsVariant.
	fmt.Fprintf(b, "// AsVariant returns the __kind__-tagged wire representation.\n")
	if len(v.fields) == 0 {
		fmt.Fprintf(b, "func (%s) AsVariant() md_tmpl.Variant {\n", typeName)
		fmt.Fprintf(b, "\treturn md_tmpl.Variant{Kind: %q}\n", v.name)
		b.WriteString("}\n\n")
	} else {
		fmt.Fprintf(b, "func (v %s) AsVariant() md_tmpl.Variant {\n", typeName)
		fmt.Fprintf(b, "\treturn md_tmpl.Variant{\n")
		fmt.Fprintf(b, "\t\tKind: %q,\n", v.name)
		fmt.Fprintf(b, "\t\tFields: map[string]any{\n")
		for _, f := range v.fields {
			fmt.Fprintf(b, "\t\t\t%q: v.%s,\n", f.name, toPascalCase(f.name))
		}
		b.WriteString("\t\t},\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	// MarshalJSON.
	if len(v.fields) == 0 {
		fmt.Fprintf(b, "// MarshalJSON encodes the unit variant as the bare string %q.\n", v.name)
		fmt.Fprintf(b, "func (%s) MarshalJSON() ([]byte, error) { return json.Marshal(%q) }\n\n", typeName, v.name)
	} else {
		fmt.Fprintf(b, "// MarshalJSON encodes the variant as {\"__kind__\":%q,...}.\n", v.name)
		fmt.Fprintf(b, "func (v %s) MarshalJSON() ([]byte, error) { return v.AsVariant().MarshalJSON() }\n\n", typeName)
	}

	// Constructor.
	if len(v.fields) == 0 {
		fmt.Fprintf(b, "// New%s constructs the %q variant of %s.\n", typeName, v.name, enumName)
		fmt.Fprintf(b, "func New%s() %s { return %s{} }\n\n", typeName, typeName, typeName)
	} else {
		params := make([]string, len(v.fields))
		assigns := make([]string, len(v.fields)+1)
		assigns[0] = fmt.Sprintf("TaggedVariant: md_tmpl.NewTaggedVariant(%q)", v.name)
		for i, f := range v.fields {
			goType := c.resolveType(f.name, f.typeNode)
			paramName := toCamelCase(f.name)
			params[i] = fmt.Sprintf("%s %s", paramName, goType)
			assigns[i+1] = fmt.Sprintf("%s: %s", toPascalCase(f.name), paramName)
		}
		fmt.Fprintf(b, "// New%s constructs the %q variant of %s.\n", typeName, v.name, enumName)
		fmt.Fprintf(b, "func New%s(%s) %s {\n", typeName, strings.Join(params, ", "), typeName)
		fmt.Fprintf(b, "\treturn %s{%s}\n", typeName, strings.Join(assigns, ", "))
		b.WriteString("}\n\n")
	}
}

// emitVariantUnmarshaler writes Unmarshal<Name>, which decodes either wire form
// (a bare string or a __kind__-tagged object) into the sealed interface.
func (c *codegenContext) emitVariantUnmarshaler(b *strings.Builder, enumName string, variants []variantNode) {
	fmt.Fprintf(b, "// Unmarshal%s decodes a %s from its wire representation: a bare string\n", enumName, enumName)
	fmt.Fprintf(b, "// for unit variants, or a {\"__kind__\":...} object for data variants.\n")
	fmt.Fprintf(b, "func Unmarshal%s(data []byte) (%s, error) {\n", enumName, enumName)
	fmt.Fprintf(b, "\tkind, err := md_tmpl.VariantKind(data)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(b, "\tswitch kind {\n")
	for _, v := range variants {
		typeName := enumName + v.name
		fmt.Fprintf(b, "\tcase %q:\n", v.name)
		if len(v.fields) == 0 {
			fmt.Fprintf(b, "\t\treturn %s{}, nil\n", typeName)
		} else {
			fmt.Fprintf(b, "\t\tvar v %s\n", typeName)
			fmt.Fprintf(b, "\t\tif err := json.Unmarshal(data, &v); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
			fmt.Fprintf(b, "\t\treturn v, nil\n")
		}
	}
	fmt.Fprintf(b, "\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(%q, kind)\n", "unknown "+enumName+" variant: %q")
	fmt.Fprintf(b, "\t}\n")
	b.WriteString("}\n\n")
}

// ---------------------------------------------------------------------------
// TypeSpec parser
// ---------------------------------------------------------------------------

// typeKind classifies a parsed type.
type typeKind int

const (
	kindStr typeKind = iota
	kindInt
	kindFloat
	kindBool
	kindList
	kindStruct
	kindEnum
	kindOption     // option(T) — nullable wrapper.
	kindScalarList // scalar_list(T) — homogeneous typed list.
	kindTmpl       // tmpl(...) or tmpl — sub-template parameter.
	kindAlias      // Unresolved type alias.
)

// typeNode is a parsed type specification.
type typeNode struct {
	kind      typeKind
	fields    []fieldNode   // For list and struct.
	variants  []variantNode // For enum.
	innerType *typeNode     // For option, scalar_list, and tmpl.
	aliasName string        // For unresolved type alias.
}

// fieldNode is a name-type pair inside a list/struct/variant.
type fieldNode struct {
	name     string
	typeNode typeNode
}

// variantNode is one variant of an enum.
type variantNode struct {
	name   string
	fields []fieldNode // Empty for unit variants.
}

// parseTypeSpec parses a TypeSpec string like "str", "list(x = str, y = int)",
// "enum(A, B(x = str))", etc.
func parseTypeSpec(spec string) (typeNode, error) {
	spec = strings.TrimSpace(spec)
	p := &typeParser{input: spec}
	node, err := p.parseType()
	if err != nil {
		return typeNode{}, err
	}
	return node, nil
}

// typeParser is a simple recursive-descent parser for TypeSpec strings.
type typeParser struct {
	input string
	pos   int
}

func (p *typeParser) parseType() (typeNode, error) {
	p.skipWhitespace()
	ident := p.readIdent()
	if ident == "" {
		return typeNode{}, fmt.Errorf("expected type identifier at position %d in %q", p.pos, p.input)
	}

	switch ident {
	case "str":
		return typeNode{kind: kindStr}, nil
	case "int":
		return typeNode{kind: kindInt}, nil
	case "float":
		return typeNode{kind: kindFloat}, nil
	case "bool":
		return typeNode{kind: kindBool}, nil
	case "list":
		return p.parseCompound(kindList)
	case "struct":
		return p.parseCompound(kindStruct)
	case "enum":
		return p.parseEnum()
	case "option":
		return p.parseWrapped(kindOption)
	case "scalar_list":
		return p.parseWrapped(kindScalarList)
	case "tmpl":
		return p.parseCompound(kindTmpl)
	default:
		// Type alias or unknown type. The engine resolves
		// aliases at runtime.
		return typeNode{kind: kindAlias, aliasName: ident}, nil
	}
}

// parseWrapped handles option(T) and scalar_list(T) — types wrapping a single inner type.
func (p *typeParser) parseWrapped(kind typeKind) (typeNode, error) {
	p.skipWhitespace()
	if !p.consume('(') {
		return typeNode{}, fmt.Errorf("expected '(' after type keyword at position %d in %q", p.pos, p.input)
	}
	p.skipWhitespace()

	inner, err := p.parseType()
	if err != nil {
		return typeNode{}, fmt.Errorf("parsing inner type: %w", err)
	}

	p.skipWhitespace()
	if !p.consume(')') {
		return typeNode{}, fmt.Errorf("expected ')' at position %d in %q", p.pos, p.input)
	}

	return typeNode{kind: kind, innerType: &inner}, nil
}

func (p *typeParser) parseCompound(kind typeKind) (typeNode, error) {
	p.skipWhitespace()
	if !p.consume('(') {
		// Bare list/struct without fields.
		return typeNode{kind: kind}, nil
	}

	// For list types, check if this is a scalar list (e.g., list(str))
	// by peeking ahead: if the first token is a type keyword not followed
	// by '=', it's a scalar list.
	if kind == kindList {
		saved := p.pos
		p.skipWhitespace()
		ident := p.readIdent()
		p.skipWhitespace()
		if ident != "" && p.peek() == ')' {
			// It's a scalar list like list(str).
			p.pos++ // consume ')'
			innerNode, err := parseTypeSpec(ident)
			if err != nil {
				return typeNode{}, fmt.Errorf("parsing scalar list element type: %w", err)
			}
			return typeNode{kind: kindScalarList, innerType: &innerNode}, nil
		}
		// Not a scalar list — restore position and parse as normal fields.
		p.pos = saved
	}

	fields, err := p.parseFields(')')
	if err != nil {
		return typeNode{}, err
	}

	return typeNode{kind: kind, fields: fields}, nil
}

func (p *typeParser) parseFields(closer rune) ([]fieldNode, error) {
	var fields []fieldNode
	for {
		p.skipWhitespace()
		if p.peek() == byte(closer) {
			p.pos++
			break
		}
		if len(fields) > 0 {
			if !p.consume(',') {
				return nil, fmt.Errorf("expected ',' or '%c' at position %d in %q", closer, p.pos, p.input)
			}
			p.skipWhitespace()
		}

		name := p.readIdent()
		if name == "" {
			return nil, fmt.Errorf("expected field name at position %d in %q", p.pos, p.input)
		}
		p.skipWhitespace()
		if !p.consume('=') {
			return nil, fmt.Errorf("expected '=' after field name %q at position %d in %q", name, p.pos, p.input)
		}
		p.skipWhitespace()

		fieldType, err := p.parseType()
		if err != nil {
			return nil, fmt.Errorf("parsing type for field %q: %w", name, err)
		}
		fields = append(fields, fieldNode{name: name, typeNode: fieldType})
	}
	return fields, nil
}

func (p *typeParser) parseEnum() (typeNode, error) {
	p.skipWhitespace()
	if !p.consume('(') {
		return typeNode{}, fmt.Errorf("expected '(' after 'enum' at position %d in %q", p.pos, p.input)
	}

	var variants []variantNode
	for {
		p.skipWhitespace()
		if p.peek() == ')' {
			p.pos++
			break
		}
		if len(variants) > 0 {
			if !p.consume(',') {
				return typeNode{}, fmt.Errorf("expected ',' or ')' at position %d in %q", p.pos, p.input)
			}
			p.skipWhitespace()
		}

		name := p.readIdent()
		if name == "" {
			return typeNode{}, fmt.Errorf("expected variant name at position %d in %q", p.pos, p.input)
		}

		p.skipWhitespace()
		var fields []fieldNode
		if p.peek() == '(' {
			p.pos++ // consume '('
			var err error
			fields, err = p.parseFields(')')
			if err != nil {
				return typeNode{}, fmt.Errorf("parsing variant %q fields: %w", name, err)
			}
		}

		variants = append(variants, variantNode{name: name, fields: fields})
	}

	return typeNode{kind: kindEnum, variants: variants}, nil
}

func (p *typeParser) skipWhitespace() {
	for p.pos < len(p.input) && (p.input[p.pos] == ' ' || p.input[p.pos] == '\t' || p.input[p.pos] == '\n' || p.input[p.pos] == '\r') {
		p.pos++
	}
}

func (p *typeParser) readIdent() string {
	start := p.pos
	for p.pos < len(p.input) {
		ch := p.input[p.pos]
		if ch == '_' || (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9' && p.pos > start) {
			p.pos++
		} else {
			break
		}
	}
	return p.input[start:p.pos]
}

func (p *typeParser) peek() byte {
	if p.pos >= len(p.input) {
		return 0
	}
	return p.input[p.pos]
}

func (p *typeParser) consume(ch byte) bool {
	p.skipWhitespace()
	if p.pos < len(p.input) && p.input[p.pos] == ch {
		p.pos++
		return true
	}
	return false
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// toPascalCase converts snake_case or kebab-case to PascalCase.
func toPascalCase(s string) string {
	var result strings.Builder
	capitalizeNext := true
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' {
			capitalizeNext = true
			continue
		}
		if capitalizeNext {
			result.WriteRune(unicode.ToUpper(r))
			capitalizeNext = false
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

// goKeywords is the set of reserved Go identifiers that must not be used as
// generated parameter names.
var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

// toCamelCase converts snake_case or kebab-case to camelCase, suitable for use
// as a local parameter name. If the result collides with a Go keyword, an
// underscore is appended to keep the generated code valid.
func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if pascal == "" {
		return pascal
	}
	runes := []rune(pascal)
	runes[0] = unicode.ToLower(runes[0])
	camel := string(runes)
	if goKeywords[camel] {
		return camel + "_"
	}
	return camel
}
